### ISSUE TITLE
New Heroku deploys fail due to unmet mLab mongodb version

### ISSUE THREAD

**Issue by pstephenson02** [kesne/jeopardy-bot#187]
New mLab mongo sandboxes are shipped with mongo 3.x and connections to these databases require newer drivers that support SCRAM-SHA-1 (http://docs.mlab.com/connecting/#version-compatibility). Our current map resolves to mongo 2.1.x required by mongoose.

New deployments end up in this state ;((((((

```
2016-04-27T04:10:14.520077+00:00 app[web.1]: > jeopardybot@0.10.0 start:heroku /app
2016-04-27T04:10:14.520092+00:00 app[web.1]: > node --optimize_for_size --max_old_space_size=460 --gc_interval=100 lib/index
2016-04-27T04:10:15.856645+00:00 app[web.1]: info: JeopardyBot listening on port 9079
2016-04-27T04:10:15.870299+00:00 app[web.1]: 
2016-04-27T04:10:15.870316+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mongodb/lib/server.js:242
2016-04-27T04:10:15.870318+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-04-27T04:10:15.870319+00:00 app[web.1]:                                       ^
2016-04-27T04:10:15.870323+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2016-04-27T04:10:15.870324+00:00 app[web.1]:     at Object.exports._errnoException (util.js:893:11)
2016-04-27T04:10:15.870325+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:916:20)
2016-04-27T04:10:15.870325+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
```

Wishing I would have kept my old deployment around now!

I see that you're working on rebuilding this in redux via https://github.com/kesne/jeopardy-bot/issues/183 so should I assume that an upgrade path to mongo 3.x is not a priority?

**Comment by pstephenson02** [comment]
A couple stackoverflow's seem to confirm this too:
http://stackoverflow.com/questions/36082423/connecting-to-mongodb-database-on-mlab-fails-authentication
http://stackoverflow.com/questions/35935531/failed-database-connection-between-openshift-server-and-mlab-com

**Comment by kesne** [comment]
This really sucks. I'll take a look at this over the weekend and see if I can figure out a quick fix to allow deployments to work.
